添加更多canto_unique字詞
CanCLID/cantonese-classifier pull request #3
Opened 2022-09-11 20:35 UTC by AlienKevin

所有添加嘅字詞都出現喺《粵典》度（有啲仲未公開）。同埋所有字對應嘅簡體字都唔喺《现代汉语规范词典》度，或者用法非常生僻（淨係出現喺文言文度）。
* 新加嘅字：
俾噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹
* 新加嘅詞：
  - [嚇凍冷攝整揩逢淥浸激][親嚫]
  - [橫搞打傾諗攞通得唔拆]掂
  - 家[下陣]

2022-09-11 20:57 UTC, laubonghaudoi commented
唔該晒，不過我覺得個「俾」字唔應該加落去，因為呢隻字喺簡體漢字官話文圈都唔係罕見字，如果將佢當成 `canto_unique`嘅話好可能會降低分類器嘅 precision，將官話文都當成係粵文。

2022-09-11 20:58 UTC, laubonghaudoi requested changes

2022-09-11 20:58 UTC, laubonghaudoi commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
應該將個「俾」字刪走

2022-09-11 22:44 UTC, AlienKevin commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
普通話平常冇太注意到有用 俾 呢個詞，google咗之後發現好似台灣嘅法律公文有用到，唔知香港書面語喺邊種場合會用 俾 ？

2022-09-12 00:11 UTC, laubonghaudoi commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
我覺得無論香港書面語用唔用俾字，呢度都唔應該加。因為當下嘅繁體中文語料都係港台溝埋一齊嘅，冇辦法預設“呢度嘅語料如果有俾字肯定係粵文”。

而且呢個分類器嘅主要用途係「篩選出粵文語料用嚟構建粵文語料庫」，而唔係「正確分類文本」。所以個宗旨係「寧願收漏粵文，都唔好收埋官話」，即係寧願犧牲 recall 都要保證高 precision。所以無需因為個俾字導致可能收埋官話文呢個風險。

2022-09-12 02:10 UTC, AlienKevin commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
Ok，明白喇。

2022-09-12 02:14 UTC, laubonghaudoi requested changes

2022-09-12 02:14 UTC, laubonghaudoi commented on main.py
> +    r'唔[係得會好識使洗駛通知到去走]|點[樣會做得]|[琴尋]日|[而依]家|家[下陣]|[真就]係|邊[度個]|' +
```suggestion
    r'唔[係得會好識使洗駛通知到去走掂]|點[樣會做得]|[琴尋聽第]日|[而依]家|家[下陣]|[真就]係|邊[度個位]|' +
```

2022-09-12 02:21 UTC, AlienKevin commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
我可以理解需要保證粵語語料嘅precision，不過如果太過conservative可能會喺較少嘅資源中過濾掉一啲有用嘅素材。靠人嘅直覺去review呢啲字詞效率比較低，而且容易出錯（一個人嘅經歷同大眾嘅實際用法可能有出入，好似我呢次就冇意識到俾喺書面語都有用到）。多幾個人去review去有幫助，但係依然冇解決效率方面嘅問題。所以我喺issue度提咗一個proposal，通過已有嘅大型普通話語料庫嚟反向揀出廣東話特有嘅字詞。

2022-09-12 02:24 UTC, AlienKevin commented
邊科 係咪可以同 邊[度個位] 合併？

2022-09-12 02:36 UTC, hfhchan commented
我唔建議加「㨃」，呢個字普通話都用，仲幾乎係一樣意思。而家大陸好多人寫「懟」(怼)，但係唔少人包堅持寫「㨃」。

2022-09-12 02:39 UTC, hfhchan commented
係咪漏咗「噚日」？

2022-09-12 02:42 UTC, hfhchan commented
[我你][個隻條把支碌張度塊樖副]

2022-09-12 03:22 UTC, AlienKevin commented
> 我唔建議加「㨃」，呢個字普通話都用，仲幾乎係一樣意思。而家大陸好多人寫「懟」(怼)，但係唔少人堅持寫「㨃」。

我同意。「㨃」呢個字雖然喺《现代汉语规范词典》中冇收錄，但係[百度百科](https://baike.baidu.hk/item/%E3%A8%83/20725896)話有人用「㨃」嚟寫「懟」（我個人冇見過呢種用法）。Baidu搜索"㨃"輸出1,310,000個結果，相比“怼”嘅100,000,000個結果非常小（1.31%），但係有人仲係用「㨃」。

2022-09-12 03:23 UTC, AlienKevin commented
> [我你][個隻條把支碌張度塊樖副]

可唔可以加個佢變成[我你佢]？

2022-09-12 05:10 UTC, laubonghaudoi commented on main.py
> +    r'[嘅嗰啲咗佢喺咁噉冇啩哋俾畀嚟諗乜嘢閪撚𨳍瞓睇㗎餸𨋢摷喎嚿噃嚡嘥嗮啱揾喐逳噏𢳂岋糴㨃揈撳𥄫攰癐冚孻冧𡃁嚫跣𨃩瀡氹]|' +
> [我你][個隻條把支碌張度塊樖副]

我覺得呢個肯定唔可以加，因為有大量普通話文本都會有「我把」「你把」等等組合，會大幅降低個precision

2022-09-12 05:11 UTC, laubonghaudoi commented
> > [我你][個隻條把支碌張度塊樖副]
> 
> 可唔可以加個佢變成[我你佢]？不過，我覺得有啲詞可能會增加false positive。好似「我把」，「你把」呢啲都喺普通話好常用。而家我哋手寫規則呢種方式好難避免imbalance：減少咗false negative，可能就多咗false positive...

冇錯，呢個肯定唔可以加

2022-09-12 05:12 UTC, laubonghaudoi commented
> > 我唔建議加「㨃」，呢個字普通話都用，仲幾乎係一樣意思。而家大陸好多人寫「懟」(怼)，但係唔少人堅持寫「㨃」。
> 
> 我同意。「㨃」呢個字雖然喺《现代汉语规范词典》中冇收錄，但係[百度百科](https://baike.baidu.hk/item/%E3%A8%83/20725896)話有人用「㨃」嚟寫「懟」（我個人冇見過呢種用法）。Baidu搜索"㨃"輸出1,310,000個結果，相比“怼”嘅100,000,000個結果非常小（1.31%），但係有人仲係用「㨃」。

冇錯，唔可以加「㨃」，普通話文本入面好多呢隻字，而且嚴格嚟講都唔係粵文專屬字

2022-09-12 07:01 UTC, hfhchan commented
係，sor，醒唔起普通話有「我把」「你把」，我剩係掛住諗「我把扇」「你把遮」

「佢」 + 「量詞」唔使加，因為「佢」已經足以斷定係粵文

2022-09-12 11:41 UTC, AlienKevin commented
目前所有嘅changes我都implement咗，應該ready to merge。

2022-09-12 20:20 UTC, laubonghaudoi approved these changes

2022-09-12 20:21 UTC, merged